### ISSUE TITLE
A Javascript error on MacBook (High Sierra)

### ISSUE THREAD

**Issue by AshhChika** [hymm/squid-tracks#163]
I am using version 10.13.4 (High Sierra).
When I installed `squid-tracks-1.2.0-mac.zip` and open it, it said 
> A JavaScript error occurred in the main process .

Then, I cannot launch SquidTracks.
Do you have any idea ?
I attach a screen shot of error sentences.
<img width="416" alt="screenshot 2018-05-25 10 48 26" src="https://user-images.githubusercontent.com/26056715/40522082-fe57b852-6009-11e8-8ac9-d4ea6e8b171e.png">

Thank you

**Comment by mcescalante** [comment]
Are you trying to open SquidTracks from inside a mounted volume or from a hard drive? Try the following:

1. Move the application to `/Applications` (or re-mount and drag another copy to `/Applications`)
2. Open that newly copied one in Applications once (hopefully successfully opens)
3. Move the file back to wherever you are trying to run it from and see if it runs after one successful run

I was able to replicate a similar error by removing the related Application Support files for SquidTracks and then trying to open the app for the "first time ever" directly from the mounted `.dmg`. If you're already trying to run this from Applications and getting this error I can take a closer look.

**Comment by AshhChika** [comment]
Thank you for your comment.
I can open SquidTracks after I move SquidTracks to `/Applications`.
