### ISSUE TITLE
New rotation type breaks salmon run tab

### ISSUE THREAD

**Issue by Lokno** [hymm/squid-tracks#174]
This weekend brings what appears to be a brand new rotation type, all question marks with a salmon slime green color. This has broken the salmon tab (salmon.js) in the current release version because weapon is not null, but weapon.weapon is null. A new attribute has appeared, weapon.coop_special_weapon with two fields, image and name. The field name is set to "Random" for all slots, while "image" is a url to the question mark image. I haven't messed with the data for previous salmon run shifts with random slots, so I don't know if weapon.coop_special_weapon is usually available for the random weapon slots, or if it's new to this shift.

To fix the tab from showing a blank page, replace the condition on line 250 with:

`weapon.weapon == null`

To add the new question mark, the following should replace the null case:

```
  weapon.coop_special_weapon != null ? (
    <Image
      key={i}
      src={`https://app.splatoon2.nintendo.net${
        weapon.coop_special_weapon.image
      }`}
      style={{ maxHeight: 40 }}
      alt={weapon.coop_special_weapon.name}
    />
  ) : (
    <div key={i} className="mystery">
      ?
    </div>              
  )
```

**Comment by hymm** [comment]
thanks for the bug report.  fixed it in c4fd2ee2d4c86f056e1e20f37699bc70c206380d
