### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by TakuikaNinja** [hymm/squid-tracks#184]
Every time I try to log in, the program redirects to the login page.
I've also tried the session cookie method but I can't get the proxy working.

**Comment by mizoe** [comment]
same for me

**Comment by frozenpandaman** [comment]
@TakuikaNinja @mizoe 
Along with the v1.4.1 update to the app, the key used in the HMAC (which is used to generate `f`, which is needed to log in) changed, and thus we're not able to generate valid tokens anymore.

I expect we'll get it working again soon, considering we did once before already… unless they changed more stuff we don't know about yet.

See `https://github.com/frozenpandaman/splatnet2statink/issues/56` for more info.

You can get your `iksm_cookie` manually for now: https://github.com/frozenpandaman/splatnet2statink/wiki/mitmproxy-instructions

**Comment by gotmilk0112** [comment]
I still can't log in with the iksm_cookie thing. At Step #7, I can't rename the certificate, and when trying to open NSO app, it just keeps saying the connection is unstable.

**Comment by hymm** [comment]
@gotmilk0112 are you using the instructions that frozenpandaman posted above?

**Comment by frozenpandaman** [comment]
@hymm They posted about it here too (even though it wasn't part of s2s or those instructions, really) and already solved it: https://github.com/frozenpandaman/splatnet2statink/issues/66
