### ISSUE TITLE
How about fixing login?

### ISSUE THREAD

**Issue by SamB** [hymm/squid-tracks#193]
I think the safest thing would be to direct the user to nintendo.com and ask them to paste the URL for "Select this account", like [splatnet2statink](https://github.com/frozenpandaman/splatnet2statink) is doing now.

Or, you know, at least tell the user which value to copy and paste from splatnet2statink's `config.txt` as an alternative to the MITM proxy. (It's `cookie`, for some reason.)

**Comment by mathewthe2** [comment]
I managed to update the NSO Login to the newest version by only changing one file: _splatnet2.js_
If you want to build it yourself [here is the updated file](https://gist.github.com/mathewthe2/24e8451f6adcec57f1802bd1935597a6). 
I might fork the project and add updated releases.

**Comment by hymm** [comment]
@mathewthe2 Thanks.  Added your file to an official release of squid tracks.

**Comment by mathewthe2** [comment]
@hymm actually nintendo updated their version again which will require me to update project and compile the dist again. For future's sake, I might add an external request to my own server to check the latest version so we don't have to manage this repo so frequently...
