### ISSUE TITLE
Images cannot be loaded

### ISSUE THREAD

**Issue by ara-ta3** [hymm/squid-tracks#210]
I use squidtracks version 1.3.3.
It cannot load most of images.

![スクリーンショット 2020-09-24 22 45 40](https://user-images.githubusercontent.com/2089153/94153404-b35e6680-feb7-11ea-86b0-776b5aa7fa29.png)

I ran it locally and devtool gave me this error.

> Failed to load resource: net::ERR_CERT_INVALID

![スクリーンショット 2020-09-24 22 34 57](https://user-images.githubusercontent.com/2089153/94152170-3b437100-feb6-11ea-8cd6-a92a4e6f7099.png)

I don't think this is a good way to do it, since it ignores the errors, but I added this code and it worked

```javascript
app.commandLine.appendSwitch('ignore-certificate-errors', 'true');
```

git diff

```patch
diff --git a/public/main/index.js b/public/main/index.js
index 0d4dd8c..26806f2 100644
--- a/public/main/index.js
+++ b/public/main/index.js
@@ -32,6 +32,7 @@ if (!isDev) {
   require('./autoupdate');
 } else {
   log.info('app running in development');
+  app.commandLine.appendSwitch('ignore-certificate-errors', 'true');
 }

 const startUrl = isDev
```

I'm not familiar with Electron, so I'll look into it more and find a better way, but I'll report back anyway.

**Comment by littlepetfrog** [comment]
I'm having the same issue:
![image](https://user-images.githubusercontent.com/42550752/94181479-2ab6da80-fe65-11ea-9bb6-8df4046d5b6b.png)

**Comment by ara-ta3** [comment]
I raised it to version 1.3.4 and it was fixed. Thanks!

https://github.com/hymm/squid-tracks/releases/tag/v1.3.4
