### ISSUE TITLE
Language of the program 

### ISSUE THREAD

**Issue by nils140102** [hymm/squid-tracks#25]
Hey. The program is really great. I am german and so with the latest update the language changed to german. However, I would like the program to still be in english. I share my results with people from around the world, and everybody understands the english names - but only german talking people know the german names. This is why it would be very cool to add a setting that allows us to freely choose the language of the program.

**Comment by hymm** [comment]
Sure.  I'll try to get it out in the next update.  I'll try and include a bunch of languages, but I won't be able to test them all.  Splatnet seems to be region locked.  I.e.  I'm in the USA and I can't see my language to Japanese.

**Comment by hymm** [comment]
out in version 0.2.4. Sorry it took so long.
