### ISSUE TITLE
Upload all battle history at once?

### ISSUE THREAD

**Issue by dofine** [hymm/squid-tracks#28]
Thanks for this awesome app! 
One tiny problem is, I can only upload battle history one by one? First time using this would require me to upload all 50 by hand. 
And the dropdown menu is too long. Not very beautiful :)
![snipaste_20170819_134658](https://user-images.githubusercontent.com/440101/29483891-01783b48-84e5-11e7-98e4-58398718d557.png)

Besides, I've posted your repo link in a Chinese game forum for splatoon. Happy to help with translation if needed,  and if Splatoon would have Chinese version.

**Comment by hymm** [comment]
yeah, I've gotten a few requests for that feature.  Now that I'm saving the stat.ink links, it's a possibility.  Before there was a problem with duplicate uploads.  I'll probably wait until after I change it so that the poller can run in the background before I implement this feature.

**Comment by hymm** [comment]
On the dropdown, it'll probably eventually turn into a grid, but that's pretty low on the roadmap at the moment.  You can also select battles from the **Last 50 Battles** table.

**Comment by dofine** [comment]
The app would freeze after using for a while. Mouse clicks don't respond.

**Comment by hymm** [comment]
I know there's a problem with no internet connection and sleep mode.  Is it one of these problems?

**Comment by hymm** [comment]
also clicking around quickly might cause a problem.  A lot of these problems will be better once I move auto upload to a background task

**Comment by hymm** [comment]
added in awhile back
