### ISSUE TITLE
Not correctly tracking latest battle

### ISSUE THREAD

**Issue by IceFlinger** [hymm/squid-tracks#29]
Appear to be having an issue after the battle count ticked from 999 to 1000, the list is being sorted in the wrong order and it appears to think 999 was the latest battle whenever checking, meaning it can't automatically upload battles as they come in.
![170820100840_d1f 1](https://user-images.githubusercontent.com/1993548/29495555-c633e090-858f-11e7-9efe-bc76b14d43c2.png)

**Comment by hymm** [comment]
thanks for the bug report.  I'll push a fix in the next release, which should come out later today (Sunday PDT)

**Comment by hymm** [comment]
ok, should be fixed in v0.2.2.  Could you check and make sure that it is?  I could only fake test it since I've only played 759 battles.

**Comment by IceFlinger** [comment]
I won't be able to test until Wednesday night since I'm in a trip, but I'll let you know

**Comment by IceFlinger** [comment]
Looks resolved to me since trying a few days ago.

**Comment by hymm** [comment]
good to hear.  Thanks
