### ISSUE TITLE
Upload fails if combo box has missing numbers.

### ISSUE THREAD

**Issue by Yogorouza** [hymm/squid-tracks#34]
If there is a missing number 1225 as shown in the picture, the "Upload to stat.ink" will fail.

![clip](https://user-images.githubusercontent.com/31218595/29530632-aaf60848-86df-11e7-8bbf-82296e0a7784.png)

**Comment by hymm** [comment]
Thanks for the bug report.  

Were you using the left and right arrows to navigate when it failed?

**Comment by Yogorouza** [comment]
Left and right arrows are not pressed.
Here's an example that fails.

ex.1
Step.1 Boot Squid Tracks and switch tab to "Battle History".
Step.2 1236 is displayed in the combo box.
Step.3 Pressing button "Upload to stat.ink" will fail. 
It does not finish while being displayed button caption as "Writing Battle #1236".

ex.2
Step.1 Boot Squid Tracks and switch tab to "Battle History".
Step.2 1236 is displayed in the combo box.
Step.3 Change the value of the combo box to 1226 using the down arrow. (Even changing the number to 1224 or 1212 is the same.)
Step.4 Pressing button "Upload to stat.ink" will fail. 
It does not finish while being displayed button caption as "Writing Battle #1226"

I'm sorry that my English is not good.

**Comment by Yogorouza** [comment]
I was late to say, thank you for useful software.

First I noticed that after battle #1236 was over.
I used the "Auto-upload to stat.ink", but I noticed that it stopped at 1224.
I remembered that it battle #1225 was interrupted with a network error.

**Comment by hymm** [comment]
I'll try recreating it with a disconnect.  

Another thing that might help is if you could upload your log.log file.  You can find it in:
C:\Users\<username>\AppData\Roaming\SquidTracks\log.log
but replace <username> with whatever your windows username is.

**Comment by Yogorouza** [comment]
Okay
[log.zip](https://github.com/hymm/squid-tracks/files/1240457/log.zip)

**Comment by Yogorouza** [comment]
For your reference, The following errors are caused by router restart and are irrelevant to game connection error.

> [2017-08-22 00:18:01:0856] [error] RequestError: Error: socket hang up

**Comment by hymm** [comment]
The 302 errors from stat.ink mean that the battle has already been uploaded.  I'll add in the next version to ignore these errors.  I also had some problems with my error handling from stat.ink which I'll fix.

I'll look a bit into the 404 and 403 errors.  Not sure what is causing those.  But I think those are coming from Nintendo.

**Comment by hymm** [comment]
There is also a problem with the arrows not working correctly when there's a missing battle. See issue #31.

**Comment by Yogorouza** [comment]
Thank you for your response.
