### ISSUE TITLE
[Mac] Cannot paste into app

### ISSUE THREAD

**Issue by crownsedge** [hymm/squid-tracks#58]
On version 0.2.4 on Mac, I can't paste in the API key as instructed. The menu bar does not display the typical "Edit" menu, right-clicking does not display the typical context menu, and Cmd+V does not function as expected. I also noticed this same behavior being exhibited at the Nintendo account sign in screen.

**Comment by mcescalante** [comment]
I can confirm that this issue is happening, just gave it a test. I believe this may be the cause https://github.com/electron/electron/issues/2591. Looks like there needs to be a `Menu` declared manually and then set through `setApplicationMenu`

**Comment by mcescalante** [comment]
@crownsedge check out the [0.3.0 release](https://github.com/hymm/squid-tracks/releases), the c&p issue (and other menu related stuff) is fixed/included there!

**Comment by crownsedge** [comment]
Looks like this is dealt with! Thanks a bunch :)
