### ISSUE TITLE
Under Player Card ranks, all modes display as SZ [Mac]

### ISSUE THREAD

**Issue by EeveeEmma** [hymm/squid-tracks#60]
They should be, from top to bottom, SZ, TC, and RM.
![screen shot 2017-09-02 at 2 32 14 pm](https://user-images.githubusercontent.com/20739859/29997840-b4868044-8feb-11e7-95d1-2c4a28a31cab.png)

**Comment by mcescalante** [comment]
Can confirm this - all changed to SZ in 0.2.4 - see https://github.com/hymm/squid-tracks/blob/fabd9660e615a1657d1879512e609721bcfa42b3/src/components/player-card.js#L31-L46

It's going to display "SZ" for all of them on all versions, not just Mac. I'll include a fix in my PR that I'll submit this afternoon but Mike may fix it before :)

**Comment by hymm** [comment]
I fixed it.  Will be in the next release

thanks for the bug report

**Comment by hymm** [comment]
Fixed in 0.3.0
