### ISSUE TITLE
Column header missing for ranks

### ISSUE THREAD

**Issue by DanSyor** [hymm/squid-tracks#7]
In battle history, players ranks got available with latest release but the column header is missing for now so every header from "weapon" to "s" (specials) is just one column left to where it's supposed to be.

**Comment by hymm** [comment]
fixed in commit https://github.com/hymm/squid-tracks/commit/1756f43bf030811ebb59a47c890d4e024dbd0096

**Comment by hymm** [comment]
fixed in 0.1.5
