### ISSUE TITLE
suggested changes for league battle

### ISSUE THREAD

**Issue by hymm** [hymm/squid-tracks#71]
These are partial, unresearched thoughts.  Take with a grain of salt
* [ ] only make one call to setState.  Making multiple calls causes reflows and is slowing down loading
* [ ] show weapon images beside weapon names
* [ ] filter for top 10 (20, 30, ect)
* [ ] make a league store like the battles store for better caching
* [ ] combine hero weapons with their normal counterpart
* [ ] show number of uses for weapons on average rating screen so there's some idea of the certainty of the average.  An alternative would be to calculate a variance.
* [ ] graphical representation?, pie charts, trends
* [ ] filter by weapon name
* [ ] sorting rank number column.  With so many rows it can be a bit tough to figure out where you are in the list when you scroll down.

**Comment by okuRaku** [comment]
Combining hero replicas probably going to be key in the next few weeks as [some number of] people switch from TTek to regular splattershot, too.

**Comment by hymm** [comment]
this stuff is better served on the squidtracks.ink website.  Though weekly summaries are not implemented yet.
