### ISSUE TITLE
Nintendo login not working

### ISSUE THREAD

**Issue by mcescalante** [hymm/squid-tracks#78]
I am having this issue for build and dev. When I log in, I click "use this account" I receive the following error:

`[15:02:27:0191] [error] Unhandled Promise Rejection in Main: TypeError: Cannot read property 'webApiServerCredential' of undefined`

I did try logging out completely and re-logging in by entering my credentials again and I get the same error.

**UPDATE:**
It seems like the auth server isn't sending a response back - I tried logging the entire thing to console and it comes back **undefined**. Function:

```js
async function getApiLogin(id_token, userinfo) {
  const resp = await request({
    method: 'POST',
    uri: 'https://api-lp1.znc.srv.nintendo.net/v1/Account/Login',
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      'X-Platform': 'Android',
      'X-ProductVersion': '1.0.4',
      'User-Agent': 'com.nintendo.znca/1.0.4 (Android/4.4.2)',
      Authorization: 'Bearer'
    },
    body: {
      parameter: {
        language: userinfo.language,
        naCountry: userinfo.country,
        naBirthday: userinfo.birthday,
        naIdToken: id_token
      }
    },
    json: true
  });

  return resp.result.webApiServerCredential.accessToken; //this returns (and resp.result) as undefined
}
```

The headers (particularly X-ProductVersion) are slightly different in [splatnet2statink](https://github.com/frozenpandaman/splatnet2statink/blob/master/iksm.py#L173) so maybe it's just some kind of mismatch in headers and Nintendo isn't issuing tokens:

```py
app_head = {
  'Host': 'api-lp1.znc.srv.nintendo.net',
  'Accept-Language': userLang,
  'User-Agent': 'com.nintendo.znca/1.1.0 (Android/7.1.2)',
  'Accept': 'application/json',
  'X-ProductVersion': '1.1.0',
  'Content-Type': 'application/json; charset=utf-8',
  'Connection': 'keep-alive',
  'Authorization': 'Bearer ' + splatoon_token["result"]["webApiServerCredential"]["accessToken"],
  'Content-Length': '37',
  'X-Platform': 'Android',
  'Accept-Encoding': 'gzip, deflate'
}
```

LAST UPDATE: **It's definitely the auth process. It's changed for 1.1.0 - [see this commit from splatnet2statink](https://github.com/frozenpandaman/splatnet2statink/commit/8e1b369eafcf3268309eda130289f50c27f4a59f#diff-6b43062aed3caf4eeba6693e4028c8ab)**

**Comment by hymm** [comment]
Yes, login process is broken.  I've been looking into it and haven't figured out how to fix it yet.  They added a new parameter in one of the steps that we don't know how to calculate.

I'll probably add the ability to input the iksm session token.  Though the process of getting the token is a little more difficult. see here https://github.com/frozenpandaman/splatnet2statink/wiki/mitmproxy-instructions

**Comment by koichim** [comment]
I guess we may be able to use some tcp capture apps like,
https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture
 running in Android to get iksm_session.

**Comment by hymm** [comment]
login process has been figured out and new login will come in 1.0.0 to be released soon
