### ISSUE TITLE
Wrong inked surface value uploaded to stat.ink for wins

### ISSUE THREAD

**Issue by DanSyor** [hymm/squid-tracks#8]
On stat.ink, the value for "Turf Inked + Bonus" lacks the 'P' character (ex: "750" instead of "750P") in the case of wins, causing the site to only display "?" for "Inked" for wins when listing battles.
Note that when editing battle stats on stat.ink, an integer value (i.e. a string of numbers not ending with 'P') seems required, so the issue for that 'P' to appear (and that value to appear in listings) may lie somewhere else.

**Comment by hymm** [comment]
looks like stat.ink expects the 1000p bonus to be applied to all wins.  I'll add in the bonus for ranked matches.

**Comment by hymm** [comment]
Fixed in 0.1.5
